backend:
  name: git-gateway

media_folder: source/images/uploads
public_folder: /images/uploads

collections:
  - name: pages
    label: Pages
    files:
      - file: "data/pages/home.yml"
        label: Homepage
        name: home
        fields:
          - label: Hero
            name: hero
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Image, name: image, widget: image}
              - {label: ButtonText, name: button_text, widget: string}

  - name: settings
    label: Settings
    files:
      - file: data/settings/navigation.yml
        label: Navigation
        name: navigation
        fields:
          - label: Navigation
            name: nav_items
            widget: list
            fields:
              - {label: Label, name: label, widget: string}
              - {label: Path, name: path, widget: string}
      - file: data/settings/contact.yml
        label: Contact
        name: contact
        fields:
          - label: Address
            name: address
            widget: string
          - label: Phone
            name: phone
            widget: string
          - label: Email
            name: email
            widget: string
