backend:
  name: git-gateway

media_folder: source/images/uploads
public_folder: /images/uploads

collections:
  - name: pages
    label: Pages
    files:
      - file: "data/pages/home.yml"
        label: Home
        name: home
        fields:
          - label: Hero
            name: hero
            widget: object
            fields:
              - {label: Image, name: image, widget: image}
              - {label: Title, name: title, widget: string}
              - {label: ButtonText, name: button_text, widget: string}
          - label: "Featured section title"
            name: featured_section_title
            widget: string
          - label: "Featured Section"
            name: featured_items
            widget: list
            fields:
              - {label: "Featured Item Image", name: featured_item_image, widget: image}
              - {label: "Where it links to", name: path, widget: string}
          - label: "Company Intro"
            name: company_intro
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Subtitle, name: subtitle, widget: string}
              - {label: Image, name: image, widget: image}
              - {label: ButtonText, name: button_text, widget: string}
      - file: "data/pages/about.yml"
        label: About
        name: about
        fields:
          - label: BackgroundImage
            name: background_image
            widget: image
          - label: Header
            name: header
            widget: string
          - label: Story
            name: story
            widget: markdown
          - label: "Offerings List"
            name: offerings_list
            widget: list
            fields:
              - {label: Icon, name: icon, widget: image}
              - {label: Text, name: text, widget: string}
      - file: "data/pages/contact.yml"
        label: Contact
        name: contact
        fields:
          - label: Title
            name: title
            widget: string
          - label: Subtitle
            name: subtitle
            widget: string
      - file: "data/pages/green.yml"
        label: Green
        name: greenInnovations
        fields:
          - label: Hero
            name: hero
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Image, name: image, widget: image}
          - label: Subtitle
            name: subtitle
            widget: string
          - label: "Green Materials"
            name: green_materials
            widget: list
            fields:
              - {label: Name, name: name, widget: string}
              - {label: Description, name: description, widget: text}
              - {label: Image, name: image, widget: image}
          - label: CTA
            name: cta
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Image, name: image, widget: image}
              - {label: ButtonText, name: button_text, widget: string}
      - file: "data/pages/products.yml"
        label: Products
        name: products
        fields:
          - label: Hero
            name: hero
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Intro, name: intro, widget: string}
              - {label: ButtonText, name: button_text, widget: string}
          - label: "Product Catalogs"
            name: product_catalogs
            widget: list
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Image, name: image, widget: image}
              - {label: "Exact name of pdf file", name: file_name, widget: string}
      - file: "data/pages/inspiration.yml"
        label: "News & Inspiration"
        name: inspiration
        fields:
          - label: Hero
            name: hero
            widget: object
            fields:
              - {label: Title, name: title, widget: string}
              - {label: Intro, name: intro, widget: string}
          - label: "News & Inspiration"
            name: inspiration_list
            widget: list
            fields:
              - {label: Image, name: image, widget: image}
              - {label: Source, name: source_link, widget: string}

  - name: settings
    label: Settings
    files:
      - file: data/settings/navigation.yml
        label: Navigation
        name: navigation
        fields:
          - label: Navigation
            name: nav_items
            widget: list
            fields:
              - {label: Label, name: label, widget: string}
              - {label: Path, name: path, widget: string}
      - file: data/settings/contact.yml
        label: Contact
        name: contact
        fields:
          - label: Address
            name: address
            widget: string
          - label: Phone
            name: phone
            widget: string
          - label: Email
            name: email
            widget: string
