jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'   # keep 2.7 for older Middleman sites
          bundler-cache: false  # we'll run bundler ourselves after locking platforms
      - run: bundle lock --add-platform x86_64-linux
      - run: bundle lock --add-platform ruby
      - run: bundle install --jobs 4
      - run: bundle exec middleman build --clean
      - uses: actions/upload-pages-artifact@v3
        with:
          path: build

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
